export const PASSANGER_LIST_REQUSTED = 'PASSANGER_LIST_REQUSTED'
export const PASSANGER_LIST_SUCCESS = 'PASSANGER_LIST_SUCCESS'
export const PASSANGER_LIST_ERROR = 'PASSANGER_LIST_ERROR'

export const PASSANGER_LIST_DELETE_REQUEST = 'PASSANGER_LIST_DELETE_REQUEST'
export const PASSANGER_LIST_DELETE_SUCCESS = 'PASSANGER_LIST_DELETE_SUCCESS'
export const PASSANGER_LIST_DELETE_ERROR = 'PASSANGER_LIST_DELETE_ERROR'

export const PASSANGER_LIST_UPDATE_REQUEST = 'PASSANGER_LIST_UPDATE_REQUEST'
export const PASSANGER_LIST_UPDATE_SUCCESS = 'PASSANGER_LIST_UPDATE_SUCCESS'
export const PASSANGER_LIST_UPDATE_ERROR = 'PASSANGER_LIST_UPDATE_ERROR'

